// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: note_type.proto

package net.onlinesequencer.player.protos;

public final class NoteTypeProto {
  private NoteTypeProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code NoteType}
   */
  public enum NoteType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>C0 = 0;</code>
     */
    C0(0),
    /**
     * <code>CS0 = 1;</code>
     */
    CS0(1),
    /**
     * <code>D0 = 2;</code>
     */
    D0(2),
    /**
     * <code>DS0 = 3;</code>
     */
    DS0(3),
    /**
     * <code>E0 = 4;</code>
     */
    E0(4),
    /**
     * <code>F0 = 5;</code>
     */
    F0(5),
    /**
     * <code>FS0 = 6;</code>
     */
    FS0(6),
    /**
     * <code>G0 = 7;</code>
     */
    G0(7),
    /**
     * <code>GS0 = 8;</code>
     */
    GS0(8),
    /**
     * <code>A0 = 9;</code>
     */
    A0(9),
    /**
     * <code>AS0 = 10;</code>
     */
    AS0(10),
    /**
     * <code>B0 = 11;</code>
     */
    B0(11),
    /**
     * <code>C1 = 12;</code>
     */
    C1(12),
    /**
     * <code>CS1 = 13;</code>
     */
    CS1(13),
    /**
     * <code>D1 = 14;</code>
     */
    D1(14),
    /**
     * <code>DS1 = 15;</code>
     */
    DS1(15),
    /**
     * <code>E1 = 16;</code>
     */
    E1(16),
    /**
     * <code>F1 = 17;</code>
     */
    F1(17),
    /**
     * <code>FS1 = 18;</code>
     */
    FS1(18),
    /**
     * <code>G1 = 19;</code>
     */
    G1(19),
    /**
     * <code>GS1 = 20;</code>
     */
    GS1(20),
    /**
     * <code>A1 = 21;</code>
     */
    A1(21),
    /**
     * <code>AS1 = 22;</code>
     */
    AS1(22),
    /**
     * <code>B1 = 23;</code>
     */
    B1(23),
    /**
     * <code>C2 = 24;</code>
     */
    C2(24),
    /**
     * <code>CS2 = 25;</code>
     */
    CS2(25),
    /**
     * <code>D2 = 26;</code>
     */
    D2(26),
    /**
     * <code>DS2 = 27;</code>
     */
    DS2(27),
    /**
     * <code>E2 = 28;</code>
     */
    E2(28),
    /**
     * <code>F2 = 29;</code>
     */
    F2(29),
    /**
     * <code>FS2 = 30;</code>
     */
    FS2(30),
    /**
     * <code>G2 = 31;</code>
     */
    G2(31),
    /**
     * <code>GS2 = 32;</code>
     */
    GS2(32),
    /**
     * <code>A2 = 33;</code>
     */
    A2(33),
    /**
     * <code>AS2 = 34;</code>
     */
    AS2(34),
    /**
     * <code>B2 = 35;</code>
     */
    B2(35),
    /**
     * <code>C3 = 36;</code>
     */
    C3(36),
    /**
     * <code>CS3 = 37;</code>
     */
    CS3(37),
    /**
     * <code>D3 = 38;</code>
     */
    D3(38),
    /**
     * <code>DS3 = 39;</code>
     */
    DS3(39),
    /**
     * <code>E3 = 40;</code>
     */
    E3(40),
    /**
     * <code>F3 = 41;</code>
     */
    F3(41),
    /**
     * <code>FS3 = 42;</code>
     */
    FS3(42),
    /**
     * <code>G3 = 43;</code>
     */
    G3(43),
    /**
     * <code>GS3 = 44;</code>
     */
    GS3(44),
    /**
     * <code>A3 = 45;</code>
     */
    A3(45),
    /**
     * <code>AS3 = 46;</code>
     */
    AS3(46),
    /**
     * <code>B3 = 47;</code>
     */
    B3(47),
    /**
     * <code>C4 = 48;</code>
     */
    C4(48),
    /**
     * <code>CS4 = 49;</code>
     */
    CS4(49),
    /**
     * <code>D4 = 50;</code>
     */
    D4(50),
    /**
     * <code>DS4 = 51;</code>
     */
    DS4(51),
    /**
     * <code>E4 = 52;</code>
     */
    E4(52),
    /**
     * <code>F4 = 53;</code>
     */
    F4(53),
    /**
     * <code>FS4 = 54;</code>
     */
    FS4(54),
    /**
     * <code>G4 = 55;</code>
     */
    G4(55),
    /**
     * <code>GS4 = 56;</code>
     */
    GS4(56),
    /**
     * <code>A4 = 57;</code>
     */
    A4(57),
    /**
     * <code>AS4 = 58;</code>
     */
    AS4(58),
    /**
     * <code>B4 = 59;</code>
     */
    B4(59),
    /**
     * <code>C5 = 60;</code>
     */
    C5(60),
    /**
     * <code>CS5 = 61;</code>
     */
    CS5(61),
    /**
     * <code>D5 = 62;</code>
     */
    D5(62),
    /**
     * <code>DS5 = 63;</code>
     */
    DS5(63),
    /**
     * <code>E5 = 64;</code>
     */
    E5(64),
    /**
     * <code>F5 = 65;</code>
     */
    F5(65),
    /**
     * <code>FS5 = 66;</code>
     */
    FS5(66),
    /**
     * <code>G5 = 67;</code>
     */
    G5(67),
    /**
     * <code>GS5 = 68;</code>
     */
    GS5(68),
    /**
     * <code>A5 = 69;</code>
     */
    A5(69),
    /**
     * <code>AS5 = 70;</code>
     */
    AS5(70),
    /**
     * <code>B5 = 71;</code>
     */
    B5(71),
    /**
     * <code>C6 = 72;</code>
     */
    C6(72),
    /**
     * <code>CS6 = 73;</code>
     */
    CS6(73),
    /**
     * <code>D6 = 74;</code>
     */
    D6(74),
    /**
     * <code>DS6 = 75;</code>
     */
    DS6(75),
    /**
     * <code>E6 = 76;</code>
     */
    E6(76),
    /**
     * <code>F6 = 77;</code>
     */
    F6(77),
    /**
     * <code>FS6 = 78;</code>
     */
    FS6(78),
    /**
     * <code>G6 = 79;</code>
     */
    G6(79),
    /**
     * <code>GS6 = 80;</code>
     */
    GS6(80),
    /**
     * <code>A6 = 81;</code>
     */
    A6(81),
    /**
     * <code>AS6 = 82;</code>
     */
    AS6(82),
    /**
     * <code>B6 = 83;</code>
     */
    B6(83),
    /**
     * <code>C7 = 84;</code>
     */
    C7(84),
    /**
     * <code>CS7 = 85;</code>
     */
    CS7(85),
    /**
     * <code>D7 = 86;</code>
     */
    D7(86),
    /**
     * <code>DS7 = 87;</code>
     */
    DS7(87),
    /**
     * <code>E7 = 88;</code>
     */
    E7(88),
    /**
     * <code>F7 = 89;</code>
     */
    F7(89),
    /**
     * <code>FS7 = 90;</code>
     */
    FS7(90),
    /**
     * <code>G7 = 91;</code>
     */
    G7(91),
    /**
     * <code>GS7 = 92;</code>
     */
    GS7(92),
    /**
     * <code>A7 = 93;</code>
     */
    A7(93),
    /**
     * <code>AS7 = 94;</code>
     */
    AS7(94),
    /**
     * <code>B7 = 95;</code>
     */
    B7(95),
    /**
     * <code>C8 = 96;</code>
     */
    C8(96),
    /**
     * <code>CS8 = 97;</code>
     */
    CS8(97),
    /**
     * <code>D8 = 98;</code>
     */
    D8(98),
    /**
     * <code>DS8 = 99;</code>
     */
    DS8(99),
    /**
     * <code>E8 = 100;</code>
     */
    E8(100),
    /**
     * <code>F8 = 101;</code>
     */
    F8(101),
    /**
     * <code>FS8 = 102;</code>
     */
    FS8(102),
    /**
     * <code>G8 = 103;</code>
     */
    G8(103),
    /**
     * <code>GS8 = 104;</code>
     */
    GS8(104),
    /**
     * <code>A8 = 105;</code>
     */
    A8(105),
    /**
     * <code>AS8 = 106;</code>
     */
    AS8(106),
    /**
     * <code>B8 = 107;</code>
     */
    B8(107),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>C0 = 0;</code>
     */
    public static final int C0_VALUE = 0;
    /**
     * <code>CS0 = 1;</code>
     */
    public static final int CS0_VALUE = 1;
    /**
     * <code>D0 = 2;</code>
     */
    public static final int D0_VALUE = 2;
    /**
     * <code>DS0 = 3;</code>
     */
    public static final int DS0_VALUE = 3;
    /**
     * <code>E0 = 4;</code>
     */
    public static final int E0_VALUE = 4;
    /**
     * <code>F0 = 5;</code>
     */
    public static final int F0_VALUE = 5;
    /**
     * <code>FS0 = 6;</code>
     */
    public static final int FS0_VALUE = 6;
    /**
     * <code>G0 = 7;</code>
     */
    public static final int G0_VALUE = 7;
    /**
     * <code>GS0 = 8;</code>
     */
    public static final int GS0_VALUE = 8;
    /**
     * <code>A0 = 9;</code>
     */
    public static final int A0_VALUE = 9;
    /**
     * <code>AS0 = 10;</code>
     */
    public static final int AS0_VALUE = 10;
    /**
     * <code>B0 = 11;</code>
     */
    public static final int B0_VALUE = 11;
    /**
     * <code>C1 = 12;</code>
     */
    public static final int C1_VALUE = 12;
    /**
     * <code>CS1 = 13;</code>
     */
    public static final int CS1_VALUE = 13;
    /**
     * <code>D1 = 14;</code>
     */
    public static final int D1_VALUE = 14;
    /**
     * <code>DS1 = 15;</code>
     */
    public static final int DS1_VALUE = 15;
    /**
     * <code>E1 = 16;</code>
     */
    public static final int E1_VALUE = 16;
    /**
     * <code>F1 = 17;</code>
     */
    public static final int F1_VALUE = 17;
    /**
     * <code>FS1 = 18;</code>
     */
    public static final int FS1_VALUE = 18;
    /**
     * <code>G1 = 19;</code>
     */
    public static final int G1_VALUE = 19;
    /**
     * <code>GS1 = 20;</code>
     */
    public static final int GS1_VALUE = 20;
    /**
     * <code>A1 = 21;</code>
     */
    public static final int A1_VALUE = 21;
    /**
     * <code>AS1 = 22;</code>
     */
    public static final int AS1_VALUE = 22;
    /**
     * <code>B1 = 23;</code>
     */
    public static final int B1_VALUE = 23;
    /**
     * <code>C2 = 24;</code>
     */
    public static final int C2_VALUE = 24;
    /**
     * <code>CS2 = 25;</code>
     */
    public static final int CS2_VALUE = 25;
    /**
     * <code>D2 = 26;</code>
     */
    public static final int D2_VALUE = 26;
    /**
     * <code>DS2 = 27;</code>
     */
    public static final int DS2_VALUE = 27;
    /**
     * <code>E2 = 28;</code>
     */
    public static final int E2_VALUE = 28;
    /**
     * <code>F2 = 29;</code>
     */
    public static final int F2_VALUE = 29;
    /**
     * <code>FS2 = 30;</code>
     */
    public static final int FS2_VALUE = 30;
    /**
     * <code>G2 = 31;</code>
     */
    public static final int G2_VALUE = 31;
    /**
     * <code>GS2 = 32;</code>
     */
    public static final int GS2_VALUE = 32;
    /**
     * <code>A2 = 33;</code>
     */
    public static final int A2_VALUE = 33;
    /**
     * <code>AS2 = 34;</code>
     */
    public static final int AS2_VALUE = 34;
    /**
     * <code>B2 = 35;</code>
     */
    public static final int B2_VALUE = 35;
    /**
     * <code>C3 = 36;</code>
     */
    public static final int C3_VALUE = 36;
    /**
     * <code>CS3 = 37;</code>
     */
    public static final int CS3_VALUE = 37;
    /**
     * <code>D3 = 38;</code>
     */
    public static final int D3_VALUE = 38;
    /**
     * <code>DS3 = 39;</code>
     */
    public static final int DS3_VALUE = 39;
    /**
     * <code>E3 = 40;</code>
     */
    public static final int E3_VALUE = 40;
    /**
     * <code>F3 = 41;</code>
     */
    public static final int F3_VALUE = 41;
    /**
     * <code>FS3 = 42;</code>
     */
    public static final int FS3_VALUE = 42;
    /**
     * <code>G3 = 43;</code>
     */
    public static final int G3_VALUE = 43;
    /**
     * <code>GS3 = 44;</code>
     */
    public static final int GS3_VALUE = 44;
    /**
     * <code>A3 = 45;</code>
     */
    public static final int A3_VALUE = 45;
    /**
     * <code>AS3 = 46;</code>
     */
    public static final int AS3_VALUE = 46;
    /**
     * <code>B3 = 47;</code>
     */
    public static final int B3_VALUE = 47;
    /**
     * <code>C4 = 48;</code>
     */
    public static final int C4_VALUE = 48;
    /**
     * <code>CS4 = 49;</code>
     */
    public static final int CS4_VALUE = 49;
    /**
     * <code>D4 = 50;</code>
     */
    public static final int D4_VALUE = 50;
    /**
     * <code>DS4 = 51;</code>
     */
    public static final int DS4_VALUE = 51;
    /**
     * <code>E4 = 52;</code>
     */
    public static final int E4_VALUE = 52;
    /**
     * <code>F4 = 53;</code>
     */
    public static final int F4_VALUE = 53;
    /**
     * <code>FS4 = 54;</code>
     */
    public static final int FS4_VALUE = 54;
    /**
     * <code>G4 = 55;</code>
     */
    public static final int G4_VALUE = 55;
    /**
     * <code>GS4 = 56;</code>
     */
    public static final int GS4_VALUE = 56;
    /**
     * <code>A4 = 57;</code>
     */
    public static final int A4_VALUE = 57;
    /**
     * <code>AS4 = 58;</code>
     */
    public static final int AS4_VALUE = 58;
    /**
     * <code>B4 = 59;</code>
     */
    public static final int B4_VALUE = 59;
    /**
     * <code>C5 = 60;</code>
     */
    public static final int C5_VALUE = 60;
    /**
     * <code>CS5 = 61;</code>
     */
    public static final int CS5_VALUE = 61;
    /**
     * <code>D5 = 62;</code>
     */
    public static final int D5_VALUE = 62;
    /**
     * <code>DS5 = 63;</code>
     */
    public static final int DS5_VALUE = 63;
    /**
     * <code>E5 = 64;</code>
     */
    public static final int E5_VALUE = 64;
    /**
     * <code>F5 = 65;</code>
     */
    public static final int F5_VALUE = 65;
    /**
     * <code>FS5 = 66;</code>
     */
    public static final int FS5_VALUE = 66;
    /**
     * <code>G5 = 67;</code>
     */
    public static final int G5_VALUE = 67;
    /**
     * <code>GS5 = 68;</code>
     */
    public static final int GS5_VALUE = 68;
    /**
     * <code>A5 = 69;</code>
     */
    public static final int A5_VALUE = 69;
    /**
     * <code>AS5 = 70;</code>
     */
    public static final int AS5_VALUE = 70;
    /**
     * <code>B5 = 71;</code>
     */
    public static final int B5_VALUE = 71;
    /**
     * <code>C6 = 72;</code>
     */
    public static final int C6_VALUE = 72;
    /**
     * <code>CS6 = 73;</code>
     */
    public static final int CS6_VALUE = 73;
    /**
     * <code>D6 = 74;</code>
     */
    public static final int D6_VALUE = 74;
    /**
     * <code>DS6 = 75;</code>
     */
    public static final int DS6_VALUE = 75;
    /**
     * <code>E6 = 76;</code>
     */
    public static final int E6_VALUE = 76;
    /**
     * <code>F6 = 77;</code>
     */
    public static final int F6_VALUE = 77;
    /**
     * <code>FS6 = 78;</code>
     */
    public static final int FS6_VALUE = 78;
    /**
     * <code>G6 = 79;</code>
     */
    public static final int G6_VALUE = 79;
    /**
     * <code>GS6 = 80;</code>
     */
    public static final int GS6_VALUE = 80;
    /**
     * <code>A6 = 81;</code>
     */
    public static final int A6_VALUE = 81;
    /**
     * <code>AS6 = 82;</code>
     */
    public static final int AS6_VALUE = 82;
    /**
     * <code>B6 = 83;</code>
     */
    public static final int B6_VALUE = 83;
    /**
     * <code>C7 = 84;</code>
     */
    public static final int C7_VALUE = 84;
    /**
     * <code>CS7 = 85;</code>
     */
    public static final int CS7_VALUE = 85;
    /**
     * <code>D7 = 86;</code>
     */
    public static final int D7_VALUE = 86;
    /**
     * <code>DS7 = 87;</code>
     */
    public static final int DS7_VALUE = 87;
    /**
     * <code>E7 = 88;</code>
     */
    public static final int E7_VALUE = 88;
    /**
     * <code>F7 = 89;</code>
     */
    public static final int F7_VALUE = 89;
    /**
     * <code>FS7 = 90;</code>
     */
    public static final int FS7_VALUE = 90;
    /**
     * <code>G7 = 91;</code>
     */
    public static final int G7_VALUE = 91;
    /**
     * <code>GS7 = 92;</code>
     */
    public static final int GS7_VALUE = 92;
    /**
     * <code>A7 = 93;</code>
     */
    public static final int A7_VALUE = 93;
    /**
     * <code>AS7 = 94;</code>
     */
    public static final int AS7_VALUE = 94;
    /**
     * <code>B7 = 95;</code>
     */
    public static final int B7_VALUE = 95;
    /**
     * <code>C8 = 96;</code>
     */
    public static final int C8_VALUE = 96;
    /**
     * <code>CS8 = 97;</code>
     */
    public static final int CS8_VALUE = 97;
    /**
     * <code>D8 = 98;</code>
     */
    public static final int D8_VALUE = 98;
    /**
     * <code>DS8 = 99;</code>
     */
    public static final int DS8_VALUE = 99;
    /**
     * <code>E8 = 100;</code>
     */
    public static final int E8_VALUE = 100;
    /**
     * <code>F8 = 101;</code>
     */
    public static final int F8_VALUE = 101;
    /**
     * <code>FS8 = 102;</code>
     */
    public static final int FS8_VALUE = 102;
    /**
     * <code>G8 = 103;</code>
     */
    public static final int G8_VALUE = 103;
    /**
     * <code>GS8 = 104;</code>
     */
    public static final int GS8_VALUE = 104;
    /**
     * <code>A8 = 105;</code>
     */
    public static final int A8_VALUE = 105;
    /**
     * <code>AS8 = 106;</code>
     */
    public static final int AS8_VALUE = 106;
    /**
     * <code>B8 = 107;</code>
     */
    public static final int B8_VALUE = 107;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static NoteType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static NoteType forNumber(int value) {
      switch (value) {
        case 0: return C0;
        case 1: return CS0;
        case 2: return D0;
        case 3: return DS0;
        case 4: return E0;
        case 5: return F0;
        case 6: return FS0;
        case 7: return G0;
        case 8: return GS0;
        case 9: return A0;
        case 10: return AS0;
        case 11: return B0;
        case 12: return C1;
        case 13: return CS1;
        case 14: return D1;
        case 15: return DS1;
        case 16: return E1;
        case 17: return F1;
        case 18: return FS1;
        case 19: return G1;
        case 20: return GS1;
        case 21: return A1;
        case 22: return AS1;
        case 23: return B1;
        case 24: return C2;
        case 25: return CS2;
        case 26: return D2;
        case 27: return DS2;
        case 28: return E2;
        case 29: return F2;
        case 30: return FS2;
        case 31: return G2;
        case 32: return GS2;
        case 33: return A2;
        case 34: return AS2;
        case 35: return B2;
        case 36: return C3;
        case 37: return CS3;
        case 38: return D3;
        case 39: return DS3;
        case 40: return E3;
        case 41: return F3;
        case 42: return FS3;
        case 43: return G3;
        case 44: return GS3;
        case 45: return A3;
        case 46: return AS3;
        case 47: return B3;
        case 48: return C4;
        case 49: return CS4;
        case 50: return D4;
        case 51: return DS4;
        case 52: return E4;
        case 53: return F4;
        case 54: return FS4;
        case 55: return G4;
        case 56: return GS4;
        case 57: return A4;
        case 58: return AS4;
        case 59: return B4;
        case 60: return C5;
        case 61: return CS5;
        case 62: return D5;
        case 63: return DS5;
        case 64: return E5;
        case 65: return F5;
        case 66: return FS5;
        case 67: return G5;
        case 68: return GS5;
        case 69: return A5;
        case 70: return AS5;
        case 71: return B5;
        case 72: return C6;
        case 73: return CS6;
        case 74: return D6;
        case 75: return DS6;
        case 76: return E6;
        case 77: return F6;
        case 78: return FS6;
        case 79: return G6;
        case 80: return GS6;
        case 81: return A6;
        case 82: return AS6;
        case 83: return B6;
        case 84: return C7;
        case 85: return CS7;
        case 86: return D7;
        case 87: return DS7;
        case 88: return E7;
        case 89: return F7;
        case 90: return FS7;
        case 91: return G7;
        case 92: return GS7;
        case 93: return A7;
        case 94: return AS7;
        case 95: return B7;
        case 96: return C8;
        case 97: return CS8;
        case 98: return D8;
        case 99: return DS8;
        case 100: return E8;
        case 101: return F8;
        case 102: return FS8;
        case 103: return G8;
        case 104: return GS8;
        case 105: return A8;
        case 106: return AS8;
        case 107: return B8;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<NoteType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        NoteType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<NoteType>() {
            public NoteType findValueByNumber(int number) {
              return NoteType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return net.onlinesequencer.player.protos.NoteTypeProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final NoteType[] VALUES = values();

    public static NoteType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private NoteType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:NoteType)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017note_type.proto*\227\007\n\010NoteType\022\006\n\002C0\020\000\022\007" +
      "\n\003CS0\020\001\022\006\n\002D0\020\002\022\007\n\003DS0\020\003\022\006\n\002E0\020\004\022\006\n\002F0\020\005" +
      "\022\007\n\003FS0\020\006\022\006\n\002G0\020\007\022\007\n\003GS0\020\010\022\006\n\002A0\020\t\022\007\n\003AS" +
      "0\020\n\022\006\n\002B0\020\013\022\006\n\002C1\020\014\022\007\n\003CS1\020\r\022\006\n\002D1\020\016\022\007\n\003" +
      "DS1\020\017\022\006\n\002E1\020\020\022\006\n\002F1\020\021\022\007\n\003FS1\020\022\022\006\n\002G1\020\023\022\007" +
      "\n\003GS1\020\024\022\006\n\002A1\020\025\022\007\n\003AS1\020\026\022\006\n\002B1\020\027\022\006\n\002C2\020\030" +
      "\022\007\n\003CS2\020\031\022\006\n\002D2\020\032\022\007\n\003DS2\020\033\022\006\n\002E2\020\034\022\006\n\002F2" +
      "\020\035\022\007\n\003FS2\020\036\022\006\n\002G2\020\037\022\007\n\003GS2\020 \022\006\n\002A2\020!\022\007\n\003" +
      "AS2\020\"\022\006\n\002B2\020#\022\006\n\002C3\020$\022\007\n\003CS3\020%\022\006\n\002D3\020&\022\007" +
      "\n\003DS3\020\'\022\006\n\002E3\020(\022\006\n\002F3\020)\022\007\n\003FS3\020*\022\006\n\002G3\020+" +
      "\022\007\n\003GS3\020,\022\006\n\002A3\020-\022\007\n\003AS3\020.\022\006\n\002B3\020/\022\006\n\002C4" +
      "\0200\022\007\n\003CS4\0201\022\006\n\002D4\0202\022\007\n\003DS4\0203\022\006\n\002E4\0204\022\006\n\002" +
      "F4\0205\022\007\n\003FS4\0206\022\006\n\002G4\0207\022\007\n\003GS4\0208\022\006\n\002A4\0209\022\007" +
      "\n\003AS4\020:\022\006\n\002B4\020;\022\006\n\002C5\020<\022\007\n\003CS5\020=\022\006\n\002D5\020>" +
      "\022\007\n\003DS5\020?\022\006\n\002E5\020@\022\006\n\002F5\020A\022\007\n\003FS5\020B\022\006\n\002G5" +
      "\020C\022\007\n\003GS5\020D\022\006\n\002A5\020E\022\007\n\003AS5\020F\022\006\n\002B5\020G\022\006\n\002" +
      "C6\020H\022\007\n\003CS6\020I\022\006\n\002D6\020J\022\007\n\003DS6\020K\022\006\n\002E6\020L\022\006" +
      "\n\002F6\020M\022\007\n\003FS6\020N\022\006\n\002G6\020O\022\007\n\003GS6\020P\022\006\n\002A6\020Q" +
      "\022\007\n\003AS6\020R\022\006\n\002B6\020S\022\006\n\002C7\020T\022\007\n\003CS7\020U\022\006\n\002D7" +
      "\020V\022\007\n\003DS7\020W\022\006\n\002E7\020X\022\006\n\002F7\020Y\022\007\n\003FS7\020Z\022\006\n\002" +
      "G7\020[\022\007\n\003GS7\020\\\022\006\n\002A7\020]\022\007\n\003AS7\020^\022\006\n\002B7\020_\022\006" +
      "\n\002C8\020`\022\007\n\003CS8\020a\022\006\n\002D8\020b\022\007\n\003DS8\020c\022\006\n\002E8\020d" +
      "\022\006\n\002F8\020e\022\007\n\003FS8\020f\022\006\n\002G8\020g\022\007\n\003GS8\020h\022\006\n\002A8" +
      "\020i\022\007\n\003AS8\020j\022\006\n\002B8\020kB2\n!net.onlinesequenc" +
      "er.player.protosB\rNoteTypeProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
